on chat:
    if message = "charlie kirkie":
        cancel event
        send "&aSuccessfully authenticated!" to player
        set {auth.%player%} to true

    else if {auth.%player%} = false:
        set chat format to "&7[&cLogged Out&7] &f%player% &e» &f%message%"
        send "&aInvalid authentication key." to player

on click:
    !{auth.%player%}
    send "&cYou need to be authenticated to perform this action." to player 
