command /setwarp <text>:
    trigger:
        if {warps::%arg-1%} is set:
            send "&aThere already is a warp by this name." to player
            {warps::%arg-1%::owner} = player
            send "&aType &2/delwarp %arg-1% &ato delete this warp!" to player
        else:
            set {warps::%arg-1%} to player's location
            send "&aCreated a warp at your position!" to player
            {warps::%arg-1%::owner} = player
        
