on join:
    set {auth.%player%} to false
    send "&ePlease enter your authentication key to continue:"

on leave:
    delete {auth.%player%}

on chat:
    if message is "charlie kirkie":
        cancel event
        send "&aSuccessfully authenticated!" to player
        set {auth.%player%} to true
    else if {auth.%player%} is false:
        cancel event
        broadcast "&8[&7Logged Out&8] &f%player% &e» &f%message%"
        send "&aInvalid authentication key." to player
